os: linux
language: cpp
compiler: gcc
sudo: required

notifications:
  email: false

addons:
  apt:
    packages:
      - cmake
      - gcovr
      - lcov

script:
  - cmake . -DCMAKE_BUILD_TYPE=Debug -DXDG_UTILS_TESTS=On -DXDG_UTILS_CODE_COVERAGE=On
  - make ctest_coverage -j${nproc}

after_success:
  - git clone https://github.com/azubieta/python-codacy-coverage.git --depth 1
  - pushd python-codacy-coverage; sudo python setup.py install; popd;
  - python-codacy-coverage -vr code_coverage_report.xml -l cpp
