os: linux
language: cpp
compiler: gcc

notifications:
  email: false

addons:
  apt:
    packages:
      - cmake
      - gcovr
      - lcov

script:
  - cmake . -DCMAKE_BUILD_TYPE=Debug -DXDG_UTILS_CODE_COVERAGE=On
  - make
  - ctest -V
